In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,confusion_matrix

In [2]:
df = pd.read_csv(r"C:\Users\moiez\heart_2020.csv")
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  int64
 6   MentalHealth      319795 non-null  int64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  int64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(1), int64(3), object(14)
memory usage: 43.9+ MB

In [4]:
df.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [5]:
df = df.drop("AgeCategory", axis = 1)

In [6]:
enc = LabelEncoder()
enc.fit(df["Smoking"])
df["Smoking"]=enc.transform(df["Smoking"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,No,No,3,30,No,Female,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,0,No,Yes,0,0,No,Female,White,No,Yes,Very good,7,No,No,No
2,No,26.58,1,No,No,20,30,No,Male,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,0,No,No,0,0,No,Female,White,No,No,Good,6,No,No,Yes
4,No,23.71,0,No,No,28,0,Yes,Female,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,No,No,7,0,Yes,Male,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,1,No,No,0,0,No,Male,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,0,No,No,0,0,No,Female,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,0,No,No,0,0,No,Female,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,0,No,No,0,0,No,Female,Hispanic,No,Yes,Good,8,No,No,No

In [7]:
enc = LabelEncoder()
enc.fit(df["AlcoholDrinking"])
df["AlcoholDrinking"]=enc.transform(df["AlcoholDrinking"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,0,No,3,30,No,Female,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,0,0,Yes,0,0,No,Female,White,No,Yes,Very good,7,No,No,No
2,No,26.58,1,0,No,20,30,No,Male,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,0,0,No,0,0,No,Female,White,No,No,Good,6,No,No,Yes
4,No,23.71,0,0,No,28,0,Yes,Female,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,0,No,7,0,Yes,Male,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,1,0,No,0,0,No,Male,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,0,0,No,0,0,No,Female,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,0,0,No,0,0,No,Female,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,0,0,No,0,0,No,Female,Hispanic,No,Yes,Good,8,No,No,No

In [8]:
enc = LabelEncoder()
enc.fit(df["AlcoholDrinking"])
df["AlcoholDrinking"]=enc.transform(df["AlcoholDrinking"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,0,No,3,30,No,Female,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,0,0,Yes,0,0,No,Female,White,No,Yes,Very good,7,No,No,No
2,No,26.58,1,0,No,20,30,No,Male,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,0,0,No,0,0,No,Female,White,No,No,Good,6,No,No,Yes
4,No,23.71,0,0,No,28,0,Yes,Female,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,0,No,7,0,Yes,Male,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,1,0,No,0,0,No,Male,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,0,0,No,0,0,No,Female,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,0,0,No,0,0,No,Female,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,0,0,No,0,0,No,Female,Hispanic,No,Yes,Good,8,No,No,No

In [9]:
enc = LabelEncoder()
enc.fit(df["Stroke"])
df["Stroke"]=enc.transform(df["Stroke"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,0,0,3,30,No,Female,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,0,0,1,0,0,No,Female,White,No,Yes,Very good,7,No,No,No
2,No,26.58,1,0,0,20,30,No,Male,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,0,0,0,0,0,No,Female,White,No,No,Good,6,No,No,Yes
4,No,23.71,0,0,0,28,0,Yes,Female,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,0,0,7,0,Yes,Male,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,1,0,0,0,0,No,Male,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,0,0,0,0,0,No,Female,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,0,0,0,0,0,No,Female,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,0,0,0,0,0,No,Female,Hispanic,No,Yes,Good,8,No,No,No

In [10]:
enc = LabelEncoder()
enc.fit(df["DiffWalking"])
df["DiffWalking"]=enc.transform(df["DiffWalking"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,0,0,3,30,0,Female,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,0,0,1,0,0,0,Female,White,No,Yes,Very good,7,No,No,No
2,No,26.58,1,0,0,20,30,0,Male,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,0,0,0,0,0,0,Female,White,No,No,Good,6,No,No,Yes
4,No,23.71,0,0,0,28,0,1,Female,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,0,0,7,0,1,Male,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,1,0,0,0,0,0,Male,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,0,0,0,0,0,0,Female,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,0,0,0,0,0,0,Female,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,0,0,0,0,0,0,Female,Hispanic,No,Yes,Good,8,No,No,No

In [11]:
enc = LabelEncoder()
enc.fit(df["Diabetic"])
df["Diabetic"]=enc.transform(df["Diabetic"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,0,0,3,30,0,Female,White,2,Yes,Very good,5,Yes,No,Yes
1,No,20.34,0,0,1,0,0,0,Female,White,0,Yes,Very good,7,No,No,No
2,No,26.58,1,0,0,20,30,0,Male,White,2,Yes,Fair,8,Yes,No,No
3,No,24.21,0,0,0,0,0,0,Female,White,0,No,Good,6,No,No,Yes
4,No,23.71,0,0,0,28,0,1,Female,White,0,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,0,0,7,0,1,Male,Hispanic,2,No,Fair,6,Yes,No,No
319791,No,29.84,1,0,0,0,0,0,Male,Hispanic,0,Yes,Very good,5,Yes,No,No
319792,No,24.24,0,0,0,0,0,0,Female,Hispanic,0,Yes,Good,6,No,No,No
319793,No,32.81,0,0,0,0,0,0,Female,Hispanic,0,No,Good,12,No,No,No
319794,No,46.56,0,0,0,0,0,0,Female,Hispanic,0,Yes,Good,8,No,No,No

In [12]:
enc = LabelEncoder()
enc.fit(df["PhysicalActivity"])
df["PhysicalActivity"]=enc.transform(df["PhysicalActivity"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,0,0,3,30,0,Female,White,2,1,Very good,5,Yes,No,Yes
1,No,20.34,0,0,1,0,0,0,Female,White,0,1,Very good,7,No,No,No
2,No,26.58,1,0,0,20,30,0,Male,White,2,1,Fair,8,Yes,No,No
3,No,24.21,0,0,0,0,0,0,Female,White,0,0,Good,6,No,No,Yes
4,No,23.71,0,0,0,28,0,1,Female,White,0,1,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,0,0,7,0,1,Male,Hispanic,2,0,Fair,6,Yes,No,No
319791,No,29.84,1,0,0,0,0,0,Male,Hispanic,0,1,Very good,5,Yes,No,No
319792,No,24.24,0,0,0,0,0,0,Female,Hispanic,0,1,Good,6,No,No,No
319793,No,32.81,0,0,0,0,0,0,Female,Hispanic,0,0,Good,12,No,No,No
319794,No,46.56,0,0,0,0,0,0,Female,Hispanic,0,1,Good,8,No,No,No

In [13]:
enc = LabelEncoder()
enc.fit(df["HeartDisease"])
df["HeartDisease"]=enc.transform(df["HeartDisease"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3,30,0,Female,White,2,1,Very good,5,Yes,No,Yes
1,0,20.34,0,0,1,0,0,0,Female,White,0,1,Very good,7,No,No,No
2,0,26.58,1,0,0,20,30,0,Male,White,2,1,Fair,8,Yes,No,No
3,0,24.21,0,0,0,0,0,0,Female,White,0,0,Good,6,No,No,Yes
4,0,23.71,0,0,0,28,0,1,Female,White,0,1,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,Male,Hispanic,2,0,Fair,6,Yes,No,No
319791,0,29.84,1,0,0,0,0,0,Male,Hispanic,0,1,Very good,5,Yes,No,No
319792,0,24.24,0,0,0,0,0,0,Female,Hispanic,0,1,Good,6,No,No,No
319793,0,32.81,0,0,0,0,0,0,Female,Hispanic,0,0,Good,12,No,No,No
319794,0,46.56,0,0,0,0,0,0,Female,Hispanic,0,1,Good,8,No,No,No

In [14]:
enc = LabelEncoder()
enc.fit(df["Asthma"])
df["Asthma"]=enc.transform(df["Asthma"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3,30,0,Female,White,2,1,Very good,5,1,No,Yes
1,0,20.34,0,0,1,0,0,0,Female,White,0,1,Very good,7,0,No,No
2,0,26.58,1,0,0,20,30,0,Male,White,2,1,Fair,8,1,No,No
3,0,24.21,0,0,0,0,0,0,Female,White,0,0,Good,6,0,No,Yes
4,0,23.71,0,0,0,28,0,1,Female,White,0,1,Very good,8,0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,Male,Hispanic,2,0,Fair,6,1,No,No
319791,0,29.84,1,0,0,0,0,0,Male,Hispanic,0,1,Very good,5,1,No,No
319792,0,24.24,0,0,0,0,0,0,Female,Hispanic,0,1,Good,6,0,No,No
319793,0,32.81,0,0,0,0,0,0,Female,Hispanic,0,0,Good,12,0,No,No
319794,0,46.56,0,0,0,0,0,0,Female,Hispanic,0,1,Good,8,0,No,No

In [15]:
enc = LabelEncoder()
enc.fit(df["KidneyDisease"])
df["KidneyDisease"]=enc.transform(df["KidneyDisease"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3,30,0,Female,White,2,1,Very good,5,1,0,Yes
1,0,20.34,0,0,1,0,0,0,Female,White,0,1,Very good,7,0,0,No
2,0,26.58,1,0,0,20,30,0,Male,White,2,1,Fair,8,1,0,No
3,0,24.21,0,0,0,0,0,0,Female,White,0,0,Good,6,0,0,Yes
4,0,23.71,0,0,0,28,0,1,Female,White,0,1,Very good,8,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,Male,Hispanic,2,0,Fair,6,1,0,No
319791,0,29.84,1,0,0,0,0,0,Male,Hispanic,0,1,Very good,5,1,0,No
319792,0,24.24,0,0,0,0,0,0,Female,Hispanic,0,1,Good,6,0,0,No
319793,0,32.81,0,0,0,0,0,0,Female,Hispanic,0,0,Good,12,0,0,No
319794,0,46.56,0,0,0,0,0,0,Female,Hispanic,0,1,Good,8,0,0,No

In [16]:
enc = LabelEncoder()
enc.fit(df["SkinCancer"])
df["SkinCancer"]=enc.transform(df["SkinCancer"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3,30,0,Female,White,2,1,Very good,5,1,0,1
1,0,20.34,0,0,1,0,0,0,Female,White,0,1,Very good,7,0,0,0
2,0,26.58,1,0,0,20,30,0,Male,White,2,1,Fair,8,1,0,0
3,0,24.21,0,0,0,0,0,0,Female,White,0,0,Good,6,0,0,1
4,0,23.71,0,0,0,28,0,1,Female,White,0,1,Very good,8,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,Male,Hispanic,2,0,Fair,6,1,0,0
319791,0,29.84,1,0,0,0,0,0,Male,Hispanic,0,1,Very good,5,1,0,0
319792,0,24.24,0,0,0,0,0,0,Female,Hispanic,0,1,Good,6,0,0,0
319793,0,32.81,0,0,0,0,0,0,Female,Hispanic,0,0,Good,12,0,0,0
319794,0,46.56,0,0,0,0,0,0,Female,Hispanic,0,1,Good,8,0,0,0

In [17]:
enc = LabelEncoder()
enc.fit(df["GenHealth"])
df["GenHealth"]=enc.transform(df["GenHealth"])
df
# enc.inverse_transform(enc.transform(df["smoker"]))

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3,30,0,Female,White,2,1,4,5,1,0,1
1,0,20.34,0,0,1,0,0,0,Female,White,0,1,4,7,0,0,0
2,0,26.58,1,0,0,20,30,0,Male,White,2,1,1,8,1,0,0
3,0,24.21,0,0,0,0,0,0,Female,White,0,0,2,6,0,0,1
4,0,23.71,0,0,0,28,0,1,Female,White,0,1,4,8,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,Male,Hispanic,2,0,1,6,1,0,0
319791,0,29.84,1,0,0,0,0,0,Male,Hispanic,0,1,4,5,1,0,0
319792,0,24.24,0,0,0,0,0,0,Female,Hispanic,0,1,2,6,0,0,0
319793,0,32.81,0,0,0,0,0,0,Female,Hispanic,0,0,2,12,0,0,0
319794,0,46.56,0,0,0,0,0,0,Female,Hispanic,0,1,2,8,0,0,0

In [18]:
column_enc = pd.get_dummies(df["Sex"])
df = df.join(column_enc)
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Female,Male
0,0,16.60,1,0,0,3,30,0,Female,White,2,1,4,5,1,0,1,1,0
1,0,20.34,0,0,1,0,0,0,Female,White,0,1,4,7,0,0,0,1,0
2,0,26.58,1,0,0,20,30,0,Male,White,2,1,1,8,1,0,0,0,1
3,0,24.21,0,0,0,0,0,0,Female,White,0,0,2,6,0,0,1,1,0
4,0,23.71,0,0,0,28,0,1,Female,White,0,1,4,8,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,Male,Hispanic,2,0,1,6,1,0,0,0,1
319791,0,29.84,1,0,0,0,0,0,Male,Hispanic,0,1,4,5,1,0,0,0,1
319792,0,24.24,0,0,0,0,0,0,Female,Hispanic,0,1,2,6,0,0,0,1,0
319793,0,32.81,0,0,0,0,0,0,Female,Hispanic,0,0,2,12,0,0,0,1,0
319794,0,46.56,0,0,0,0,0,0,Female,Hispanic,0,1,2,8,0,0,0,1,0

In [19]:
column2_enc = pd.get_dummies(df["Race"])
df = df.join(column2_enc)
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,...,KidneyDisease,SkinCancer,Female,Male,American Indian/Alaskan Native,Asian,Black,Hispanic,Other,White
0,0,16.60,1,0,0,3,30,0,Female,White,...,0,1,1,0,0,0,0,0,0,1
1,0,20.34,0,0,1,0,0,0,Female,White,...,0,0,1,0,0,0,0,0,0,1
2,0,26.58,1,0,0,20,30,0,Male,White,...,0,0,0,1,0,0,0,0,0,1
3,0,24.21,0,0,0,0,0,0,Female,White,...,0,1,1,0,0,0,0,0,0,1
4,0,23.71,0,0,0,28,0,1,Female,White,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,Male,Hispanic,...,0,0,0,1,0,0,0,1,0,0
319791,0,29.84,1,0,0,0,0,0,Male,Hispanic,...,0,0,0,1,0,0,0,1,0,0
319792,0,24.24,0,0,0,0,0,0,Female,Hispanic,...,0,0,1,0,0,0,0,1,0,0
319793,0,32.81,0,0,0,0,0,0,Female,Hispanic,...,0,0,1,0,0,0,0,1,0,0
319794,0,46.56,0,0,0,0,0,0,Female,Hispanic,...,0,0,1,0,0,0,0,1,0,0

In [20]:
df = df.drop(["Sex","Race"],axis = 1)
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Diabetic,PhysicalActivity,...,KidneyDisease,SkinCancer,Female,Male,American Indian/Alaskan Native,Asian,Black,Hispanic,Other,White
0,0,16.60,1,0,0,3,30,0,2,1,...,0,1,1,0,0,0,0,0,0,1
1,0,20.34,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,1
2,0,26.58,1,0,0,20,30,0,2,1,...,0,0,0,1,0,0,0,0,0,1
3,0,24.21,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,1
4,0,23.71,0,0,0,28,0,1,0,1,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7,0,1,2,0,...,0,0,0,1,0,0,0,1,0,0
319791,0,29.84,1,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
319792,0,24.24,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
319793,0,32.81,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
319794,0,46.56,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0

In [21]:
X = df.drop("HeartDisease",axis = 1)
y = df["HeartDisease"]

In [22]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 51)

In [23]:
model = DecisionTreeClassifier(max_depth = 3,random_state=1)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=1)

In [24]:
model.score(X_test,y_test)

0.9150549570818806

In [25]:
y_predict = model.predict(X_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
confusion_matrix(y_predict,y_test)

array([[58334,  5227],
       [  206,   192]], dtype=int64)